SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/rampsecure
SPRING_DATASOURCE_USERNAME=greatadams
SPRING_DATASOURCE_PASSWORD=postgres
JWT_SECRET=dGF4aU5vd1NlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNQ==
JWT_EXPIRATION=28800000